var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "                                    o o      xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "                                   xxxxx                          xvx           ",
   "                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       xxxx                                                xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x         x     o   o                                    xx!x  ",
   "                                                 x!x         x                                xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                     !!!!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              xxx                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx  xx xxx     o o  x!!!!!!!!!!!!!!x                  xxx                   ",
   "                             x xxx x   xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x            xxx              x  ",
   "  x                           xx          x                              x x x           x!!!x             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx            vxv              x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx o o o  x  ",
   "  x     @           x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       xxx x       ",
   "                                                                                             o o o    x       ",
   "                   xxx                                                                                        ",
   "       !  o  !                                                x   x xxxxx xxxx  xxxxx xxxxx xxxxx x   x       ",
   "       x     x                                                x   x x     x   x     x x   x x   x x   x       ",
   "       x= o  x            x                                   xxxxx xxxxx x   x xxxxx x ! x xxxxx xxxxx       ",
   "       x     x                                                x   x x     x   x x     x   x x   x     x       ",
   "       !  o  !            o                                  xx   x xxxxx xxxx  xxxxx xxxxx xxxxx     x       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  [ "                                                                                                              ",
    "   o   o               o                    o                        o              o                         ",
    "                                                                                                              ",
    "x  =     =        =         =         =           =      x                      =     =     = x               ",
    "xxxxxxxxxx   x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     ",
    "      o                    x                     xxxxxxxxxx                                             x     ",
    "                           x                      xxxxxxxxx                                                 o ",
    "                           x                xx     xxxxxxx                                    xxxx            ",
    "     xx                o  xxx              xxxx     xxxxx                                o                  xx",
    "                         x x x        o   xxxxxx      o                o                                      ",
    "                        x  x  x @        xxxxxxxx                                      xxxx               o   ",
    "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxx                                    ",
    "         xxxxxxxxx       x                    v        v                       o                         xxx  ",
    "        x         x      x               v         v                                                          ",
    "    o  x    o      x   o x                                                  xxxxxxxx       xxxx        o      ",
    "      x             x    x                                                                                    ",
    "  o  x     xxx           x                                    o     o                   o     o      xxxxx    ",
    "    x o          x       x                                                                                    ",
    "   x    x              xxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxx   xxxx            x",
    "  xxxxx     x         x!!x            x                                v!!!!!!!!!!!!!!!!!!   !!!!!!!!!!!!!!!!x",
    "         x     x     x!!!!x          x                 o               vx!!!!!!!!!!!!!!!!! o !!!!!!!!!!!!!!!!x",
    "         x     x    x!!!!!!x        x                           o   o  vx!!!!!!!!!!!!!!!!!   !!!!!!!!!!!!!!!!x",
    "          x x      x        x                        xxxx              vx!!!!!!!!!!!!!!!!!x  !!!!!!!!!!!!!!!!x",
    "                  x       o  x                                 xxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "                 x    o       x               xxxx          xxx   v!!!!!x                                     ",
    "      =       = x              x      o      x    x   o    x       xxxxxx                                     ",
    "xxx  xxxxxxxxxxxxxxxxxxxx       x            x  o  x      x   v!!!!x          x                               ",
    " x          o                   xxxxxxxxxxxxx       xxxxxx    vxxxxx                                          ",
    " x                                                  o        x                                                ",
    " xxxxxxxxxxxxxxxxxxxxxxxxx                                   vxv                                              ",
    "                          xxxxxxxxxxxxxxxxxxxxx             v   vx        x                                   ",
    "                                             x                v   v                o                          ",
    "                                             x                                                                ",
    "                                             x                                                            o   ",
    "                                             xx                        x                                      ",
    "                                             x                                           xxxxxxxxxxxxxxxxxxxxx",
    "                                             x                                                                ",
    "                                              xxxxxxxxxxx                                                     ",
    "                                                         xxx x x x xx                                         ",
    "                                                         xxx          x      x       x                        ",
    "                                                         xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   ]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
